name: Enforce Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required checklist items
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            const checklist1 = "- [x] Is the VCT completed, finalized and attached in the ticket?";
            const checklist2 = "- [x] Is the VCT completed, finalized and attached in the ticket? ";
             if (!prBody.includes(checklist1)) {
              core.setFailed("Missing or incomplete: ' Is the VCT completed, finalized and attached in the ticket?'");
            }

            if (!prBody.includes(checklist2)) {
              core.setFailed("Missing or incomplete: ' Is the VCT completed, finalized and attached in the ticket?");
            }
            console.log("✅ All required checklist items are present and checked.");
