name: Enforce Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-template:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Check for required checklist items
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || "";

            const checklist1 = "- [x] Is the VCT completed, finalized and attached in the ticket?";
            const checklist2 = "- [x] Do you have the confirmation to proceed into production via Mail?";

            if (!prBody.includes(checklist1)) {
              core.setFailed("Missing or incomplete: 'Is the VCT completed, finalized and attached in the ticket?'");
            }

            if (!prBody.includes(checklist2)) {
              core.setFailed("Missing or incomplete: 'Do you have the confirmation to proceed into production via Mail?'");
            }

            console.log("All required checklist items are present and checked.");
