name: Enforce PR Checklist

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  check-pr-template:
    name: Verify Checklist Completion
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false

    steps:
      - name: Check out PR
        uses: actions/checkout@v3

      - name: Validate Checklist in Pull Request Body
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          echo "Checking checklist..."

          # Check for both checkboxes marked as [x]
          echo "$BODY" | grep -q "\- \[x\] Is the VCT completed, finalized and attached in the ticket?" || {
            echo "❌ VCT checkbox not checked."
            exit 1
          }

          echo "$BODY" | grep -q "\- \[x\] Do you have the confirmation to proceed into production via Mail?" || {
            echo "❌ Mail confirmation checkbox not checked."
            exit 1
          }

          echo "✅ All checklist items are completed."
