name: Enforce Checklist

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Check for required checklist items
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            const checklist = "- [x] I confirm documentation is reviewed";

            if (!prBody || !prBody.includes(checklist)) {
              core.setFailed("Checklist not fully completed. Please ensure the documentation confirmation is checked.");
            } else {
              console.log("Checklist confirmed. ✅");
            }
