name: Slack Merge Alert (Main Branch Only)

on:
  pull_request:
    types: [closed]

jobs:
  notify-slack:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "Pull request merged into main:\n- Repository: ${{ github.repository }}\n- PR #: ${{ github.event.pull_request.number }}\n- Title: ${{ github.event.pull_request.title }}\n- Merged by: ${{ github.event.pull_request.merged_by.login }}\n- URL: ${{ github.event.pull_request.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
